[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 130
dimensions.lines = 45

decorations = "Buttonless"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 24
