#!/usr/bin/env zsh
#
# zsh Aliases

alias h="cd ~/"
alias ll="eza --git --time-style relative -al"
alias zs="source ~/.zshrc"
alias restore-from="git restore --source"

# tmux
alias tm="tmux"
alias tml="tmux ls"
alias tma="tmux attach -t \$(tmux ls -F '#{session_name}' | fzf)"
alias tmpl="tmuxp load ." # tmuxp load session

# Run dotfiles installer
alias dotinstall="~/.dotfiles/install"
