# ==== PATH Management ====
typeset -U path

path=(
  /usr/local/bin
  /usr/local/sbin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /usr/local/git/bin
)

# Add Homebrew
path=(/opt/homebrew/bin /opt/homebrew/sbin $path)

# Add user-specific bins
path=(~/.local/bin ~/.composer/vendor/bin $path)

# Add pnpm
export PNPM_HOME="$HOME/Library/pnpm"
[ -d "$PNPM_HOME" ] && path=($PNPM_HOME $path)

export PATH

# ==== Environment Variables ====
export LANG=en_US.UTF-8
export OP_ACCOUNT=my.1password.com

# ==== Oh My Zsh Configuration ====
export ZSH=~/.oh-my-zsh 
ZSH_THEME="robbyrussell"
plugins=(git brew node macos nvm z)

source "$ZSH/oh-my-zsh.sh"

# ==== Sources and Completions ====
[ -f /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f ~/.zsh_functions ] && source ~/.zsh_functions
[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.1password.zsh ] && source ~/.1password.zsh

# Homebrew autocomplete
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
  autoload -Uz compinit && compinit
fi

if which rbenv > /dev/null; then
  eval "$(rbenv init - zsh)"
fi

eval "$(zoxide init zsh)"

[ -s "$(brew --prefix nvm)/nvm.sh" ] && source "$(brew --prefix nvm)/nvm.sh"

eval "$(direnv hook zsh)"